### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by priithansen** [BetterBrief/silverstripe-googlemapfield#13]
Would it be possible to get a example of how this module is meant to be used?
Can't seem to figure it out on my own :\

**Comment by digitall-it** [comment]
Many years later, sorry to necropost, but the link is broken, this module seems promising but can't seem to understand how to use it propely. Created a Position dataobject, then my page has_one Position, then I added field GoogleMapField($this->Position()) in getCMSFields but didn't work.

**Comment by willmorgan** [comment]
@digitall-it In what way does it not work?

**Comment by digitall-it** [comment]
The link pointing to the docs wasn't working, so I thought that there was some complete example on how to use the class. Now I see it points to the official documentation on the module that I already read. I had to use another module so can't reproduce the error I was getting anymore, your module seems very interesting but I think it would benefit from a minimum use case.

**Comment by willmorgan** [comment]
Alright, sorry it didn't work for you. I fixed the old link as it was pointing to my old fork of the project but BetterBrief now (sort of) maintains the repo.
