### ISSUE TITLE
Map does not render after saving in CMS

### ISSUE THREAD

**Issue by dhensby** [BetterBrief/silverstripe-googlemapfield#23]
After saving in the CMS I see this:

![no map](https://dl.dropbox.com/u/3429338/Clippings/2015-02/2015-02-06_13-27-46_cjK3tglLTT.png)

**Comment by willmorgan** [comment]
Entwine issue perhaps?

**Comment by dhensby** [comment]
There is no event listener in the JS for when a page is loaded and I have NO idea how to find what events are fired.
