### ISSUE TITLE
Tag Release 1.3

### ISSUE THREAD

**Issue by stevie-mayhew** [BetterBrief/silverstripe-googlemapfield#25]
Is it possible to get a tag for this version? I don't like relying on x-dev tags :)

**Comment by willmorgan** [comment]
[Here you go](https://github.com/BetterBrief/silverstripe-googlemapfield/releases/tag/v1.3) :smile:

**Comment by stevie-mayhew** [comment]
Whoops, might have had a brain explosion. Maybe they aren't being pushed to packagist correctly as there isn't a 1.3.0 there? https://packagist.org/packages/betterbrief/silverstripe-googlemapfield

**Comment by willmorgan** [comment]
Hmm, it could be a caching issue. @dhensby, you're the repo owner on Packagist - is it possible to trigger a refresh on their side via the admin controls there?

**Comment by dhensby** [comment]
It's showing in packagist for me, though I ran an update anyway

**Comment by stevie-mayhew** [comment]
Thanks @dhensby :)
