### ISSUE TITLE
API Key configuration for frontend

### ISSUE THREAD

**Issue by mediabeastnz** [BetterBrief/silverstripe-googlemapfield#31]
Theres no easy way to use the API Key from the configuration in the frontend.

Without making a custom function you have to manually put it somewhere else e.g.

``` js
<script src="https://maps.googleapis.com/maps/api/js?key=#"></script>
```

Which means you'd have two keys in different locations.

What would be the best approach to have it in one place and have the ability to use it in the frontend?

Happy to make a pull request, just wanted to discuss first.

**Comment by dhensby** [comment]
I'd approach this project by project using `TemplateGlobalProvider` and defining global template variables to do it. 

I'm not sure it needs a solution any more specific than that...

**Comment by mediabeastnz** [comment]
But you'd never have a different API key on the frontend so it seems silly to duplicate this?

Project by project would be fine but all projects will require a key on the frontend which will need to match the backend :/

**Comment by dhensby** [comment]
@mediabeastnz sorry, I'm being a bit of an idiot - I was plowing through issues and I didn't realise this was one for `googlemapfield` rather than the core framework.

When you talk about keys for the "frontend" do you mean public site vs CMS? rather than browser vs server?

**Comment by dhensby** [comment]
I think having a global API key setting would be a bit of an overreach for this module, we shouldn't define some global convention for a project for what is a single purpose module.

If you've got a suggestion that you think is fair, then I'll listen and give fair feedback - I won't reject any PR that is on balance an improvement.

**Comment by mediabeastnz** [comment]
So this exists:
```yaml
GoogleMapField:
  default_options:
    api_key: null
```

But theres no function to use that key in the frontend. That means you either have it in your template (hardcoded) or build a function for each project that grabs the above key.

What I think would be good is being able to access `$Key` in the template just like you can access `$Latitude` or `$Zoom`.

When I say frontend I mean public site yes :)

I'm assuming most people using this module will now be setting up browser keys on google console.

**Comment by dhensby** [comment]
You can access that option anywhere if you try...

```php
$opts = Config::inst()->get('GoogleMapField', 'default_options');
$key = !empty($opts['api_key']) ? $opts['api_key'] : '';
```

So you can use your own template provider to make that globally accessible (not something I think this module should do out of the box, actually better if it could take some other config value really).

> What I think would be good is being able to access `$Key` in the template just like you can access `$Latitude` or `$Zoom`.

Those values are only available in the context of the field, surely, rather than in any template?

**Comment by BrookeNZ** [comment]
Due to the Google Map API changes, the key needs to be accessible at a template level otherwise you cannot display a map.  Cheers

**Comment by dhensby** [comment]
> Due to the Google Map API changes, the key needs to be accessible at a template level otherwise you cannot display a map. Cheers

excuse my ignorance, but isn't [this inclusion](https://github.com/BetterBrief/silverstripe-googlemapfield/blob/d6c7df6f149587377a9ac2bbccaf53990dd79ae0/code/GoogleMapField.php#L171) enough (ie: including it with the request of the google maps script)?

If not, then any PR to make it accessible the same way `$Latitude` or `$Zoom` is seems reasonable to me

**Comment by quinnmerio** [comment]
This is what I do..
googlesitemapfield.yml
```
---
Name: googlemapfield
---
GoogleMapField:
  default_options:
    api_key: ABC123xxxyyyetc12345678
    default_field_values:
      Latitude: 0
      Longitude: 0
```


in themes - Page.ss
<script src="https://maps.googleapis.com/maps/api/js?key={$GmapKey}"></script>

In mysite - Page.php
```
// Get Gmap key we store in googlemapfield.yml
	public function GmapKey(){
		$key = GoogleMapField::config()->default_options['api_key'];
		return $key;
	}
```

**Comment by dhensby** [comment]
looks like a sensible way to go about it. thanks.
